/**
 * Ära 1 – Hafen (docs/03 §5). Zahlen sind Annahmen (A), belegt durch das Balancing-Gate
 * (`npm run simulate -w packages/sim`, Report `docs/balance-report.md`).
 */
import type { EraDef } from '../types.ts';

export const harbor: EraDef = {
  id: 'harbor',
  currency: 'harbor',
  price: 1,
  loadBase: 20,
  tierBuilding: 'shipyard',
  buildings: [
    {
      id: 'pier',
      stage: 'arrival',
      effect: 'vehicles',
      perLevel: 0.05,
      baseCost: 15,
      growth: 1.11,
      startLevel: 1,
      unlockAtLifetime: 0,
    },
    {
      id: 'crane',
      stage: 'unload',
      effect: 'goods',
      perLevel: 12,
      baseCost: 50,
      growth: 1.11,
      startLevel: 0,
      unlockAtLifetime: 0,
    },
    {
      id: 'warehouse',
      stage: 'sales',
      effect: 'goods',
      perLevel: 1.2,
      baseCost: 25,
      growth: 1.09,
      startLevel: 1,
      unlockAtLifetime: 0,
    },
    {
      id: 'fishMarket',
      stage: 'sales',
      effect: 'goods',
      perLevel: 8,
      baseCost: 600,
      growth: 1.1,
      startLevel: 0,
      unlockAtLifetime: 500,
    },
    {
      id: 'lighthouse',
      stage: 'arrival',
      effect: 'vehiclesPct',
      perLevel: 0.15,
      baseCost: 2_000,
      growth: 1.1,
      startLevel: 0,
      unlockAtLifetime: 40_000,
    },
    {
      id: 'shipyard',
      stage: 'arrival',
      effect: 'loadPct',
      perLevel: 0.25,
      baseCost: 1_000,
      growth: 1.07,
      startLevel: 0,
      unlockAtLifetime: 100_000,
    },
    {
      id: 'customs',
      stage: 'sales',
      effect: 'goods',
      perLevel: 60,
      baseCost: 8_000,
      growth: 1.09,
      startLevel: 0,
      unlockAtLifetime: 500_000,
    },
  ],
  vehicles: [
    { id: 'fishingBoat', good: 'fish', fromLevel: 0 },
    { id: 'cutter', good: 'fish', fromLevel: 5 },
    { id: 'freighter', good: 'crates', fromLevel: 12 },
    { id: 'containerShip', good: 'containers', fromLevel: 20 },
  ],
  goal: { id: 'spaceportPier', cost: 7e8, unlockAtLifetime: 1e6 },
  starThreshold: 4e6,
};
